import React from 'react'

const Footer = () => {
  return (
    <div className='my-7'>
        <h2 className='text-center text-gray-300 text-lg'>Generated by Trip Hub AI Trip Planner</h2>
    </div>
  )
}

export default Footer